name: Bug Report Form
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - null
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        ## Before You Submit
        - [ ] The issue you are about to raise has not been reported yet
        - [ ] You have tested it on the latest (master branch) version of CausalNex
        - [ ] You are able to reproduce it
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Short description of the problem here.
      description: Also include steps to reproduce the problem.
      placeholder: Short description of the problem here.
      value: "Short description of the problem here."
    validations:
      required: true
  - type: dropdown
    id: causalnex-version
    attributes:
      label: CausalNex Version
      description: What version of CausalNex are you running?
      options:
        - 0.12.0 (latest)
        - 0.11.2
        - 0.11.1
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you running?
      options:
        - 3.11.3 (latest)
        - 3.11.2
        - 3.11.1
        - 3.11.0
        - others
    validations:
      required: true
  - type: textarea
    id: code-output
    attributes:
      label: Relevant code snippet
      description: Please copy and paste any relevant code snippet. This will be automatically formatted into code, so no need for backticks.
      render: Python
      placeholder: print("hello world")
  - type: textarea
    id: logs-output
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      placeholder: ZeroDivisionError: division by zero
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
